<?php

/**
 * @file
 * Handle install / uninstall events for the module.
 */

/**
 * Implements hook_install().
 *
 * Copies migration source files to the public:// directory.
 */
function blog_import_install() {

  // Prepare destination directory.
  $dest_directory = 'public://blog-images';
  file_prepare_directory($dest_directory, FILE_CREATE_DIRECTORY);

  // Copy files to destination directory.
  foreach(_blog_import_source_files() as $filename => $file) {
    file_unmanaged_copy($file->uri, $dest_directory . '/' . $file->filename, FILE_EXISTS_REPLACE);
  }

}

/**
 * Implements hook_uninstall().
 *
 * Deletes migration source files created during installation.
 */
function blog_import_uninstall() {
  $dest_directory = 'public://blog-images';
  file_unmanaged_delete_recursive($dest_directory);
}

/**
 * Get a list of import source files.
 *
 * @return array
 *   Import source files.
 */
function _blog_import_source_files() {
  $dirname = drupal_get_path('module', 'blog_import') . '/blog-images';
  return file_scan_directory($dirname, '/.*/', [
    'recurse' => FALSE,
    'key' => 'filename',
  ]);
}
