<?php

/**
 * @file
 * Handle install / uninstall events for the module.
 */

/**
 * Implements hook_install().
 *
 * Copies migration source files to the public:// directory.
 */
function taxonomy_data_install() {

  // Prepare destination directory.
  $dest_directory = 'public://product-images';
  file_prepare_directory($dest_directory, FILE_CREATE_DIRECTORY);

  // Copy files to destination directory.
  foreach(_taxonomy_data_source_files() as $filename => $file) {
    file_unmanaged_copy($file->uri, $dest_directory . '/' . $file->filename, FILE_EXISTS_REPLACE);
  }

}

/**
 * Implements hook_uninstall().
 *
 * Deletes migration source files created during installation.
 */
function taxonomy_data_uninstall() {
  $dest_directory = 'public://product-images';
  file_unmanaged_delete_recursive($dest_directory);
}
