<?php

/**
 * Implements hook_form_FORM_ID_alter() for form 'commerce_checkout_flow_multistep_default'.
 */


function payment_bill_later_form_commerce_checkout_flow_custom_checkout_flow_alter(&$form, $form_state) {

  if (isset($form['payment_information']['payment_method']['#default_value'])){
    if ($form['payment_information']['payment_method']['#default_value'] == 'bill_me_later'){
      $form['payment_information']['billing_information']['#access'] = FALSE;
    }
  }

}
